
export enum LearningEventType {
  DIAGNOSTIC_COMPLETED = "DIAGNOSTIC_COMPLETED",

  ROADMAP_GENERATED = "ROADMAP_GENERATED",

  TUTOR_SESSION_STARTED = "TUTOR_SESSION_STARTED",

  TUTOR_SESSION_COMPLETED = "TUTOR_SESSION_COMPLETED",

  PRACTICE_COMPLETED = "PRACTICE_COMPLETED",

  MASTERY_UPDATED = "MASTERY_UPDATED",

  XP_AWARDED = "XP_AWARDED",
}